apiVersion: v1
kind: Secret
metadata:
  name: caresync-secret
  labels:
    app: caresync
type: Opaque
data:
  # base64 encoded value for 'secretpassword'
  DB_PASSWORD: "c2VjcmV0cGFzc3dvcmQ="
  MYSQL_ROOT_PASSWORD: "c2VjcmV0cGFzc3dvcmQ="
